import crypto from 'crypto';
import { Pool, QueryResultRow } from 'pg';
import { User, Subscription, Device, WebhookEventLog, PaymentTransaction, AdminMetrics, AuditLog, SupportNote } from '../types.ts';

/** Persistent PostgreSQL repository. No demo users or process-local state are created here. */
const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl && process.env.NODE_ENV === 'production') throw new Error('DATABASE_URL is required when NODE_ENV=production');
export const pool = new Pool({ connectionString: databaseUrl, max: Number(process.env.PG_POOL_MAX || 10), ssl: databaseUrl && process.env.PGSSL !== 'false' ? { rejectUnauthorized: false } : undefined });
const one = async <T extends QueryResultRow>(sql: string, values: unknown[] = []) => (await pool.query<T>(sql, values)).rows[0] || null;
const mapUser = (r: any): User & { passwordHash?: string } => ({ id: String(r.id), email: r.email, name: r.name || undefined, role: r.role, isVerified: !!r.is_verified, twoFactorEnabled: !!r.two_factor_enabled, createdAt: new Date(r.created_at).toISOString(), updatedAt: r.updated_at ? new Date(r.updated_at).toISOString() : undefined, ...(r.password_hash ? { passwordHash: r.password_hash } : {}) });
const mapSub = (r: any): Subscription => ({ id: String(r.id), userId: String(r.user_id), planId: r.plan_id, status: r.status, provider: r.provider || 'razorpay', currentPeriodStart: new Date(r.current_period_start).toISOString(), currentPeriodEnd: new Date(r.current_period_end).toISOString(), cancelAtPeriodEnd: !!r.cancel_at_period_end, maxDevices: Number(r.max_devices), razorpaySubscriptionId: r.razorpay_subscription_id || undefined, razorpayCustomerId: r.razorpay_customer_id || undefined, razorpayPlanId: r.razorpay_plan_id || undefined, stripeCustomerId: r.stripe_customer_id || undefined, stripeSubscriptionId: r.stripe_subscription_id || undefined, paymentMethodLast4: r.payment_method_last4 || undefined, paymentMethodBrand: r.payment_method_brand || undefined, createdAt: r.created_at ? new Date(r.created_at).toISOString() : undefined, updatedAt: r.updated_at ? new Date(r.updated_at).toISOString() : undefined });
const mapDevice = (r: any): Device => ({ id: String(r.id), userId: String(r.user_id), deviceName: r.device_name, deviceType: r.device_type, hardwareFingerprint: r.hardware_fingerprint || undefined, ipAddress: r.ip_address || undefined, status: r.status, lastHeartbeatAt: r.last_heartbeat_at ? new Date(r.last_heartbeat_at).toISOString() : undefined, pairedAt: new Date(r.paired_at).toISOString() });
const mapTx = (r: any): PaymentTransaction => ({ id: String(r.id), userId: String(r.user_id), subscriptionId: r.subscription_id ? String(r.subscription_id) : undefined, provider: r.provider, providerPaymentId: r.provider_payment_id || undefined, providerOrderId: r.provider_order_id || undefined, amount: Number(r.amount), currency: r.currency, status: r.status, method: r.method || undefined, errorCode: r.error_code || undefined, errorDescription: r.error_description || undefined, createdAt: new Date(r.created_at).toISOString() });
const mapWebhook = (r: any): WebhookEventLog => ({ id: String(r.id), eventId: r.event_id, eventType: r.event_type, status: r.status, processedAt: new Date(r.processed_at).toISOString(), summary: r.summary, payload: r.payload });

export const db = {
  async findUserByEmail(email: string) { const r = await one<any>('SELECT * FROM users WHERE lower(email)=lower($1) LIMIT 1', [email.trim()]); return r ? mapUser(r) : null; },
  async findUserById(id: string) { const r = await one<any>('SELECT * FROM users WHERE id=$1', [id]); return r ? mapUser(r) : null; },
  async createUser(data: { email: string; passwordHash: string; name?: string; role?: 'customer' | 'admin' }) {
    const client = await pool.connect();
    try { await client.query('BEGIN'); const r = await client.query<any>('INSERT INTO users(email,password_hash,name,role,is_verified) VALUES(lower($1),$2,$3,$4,FALSE) RETURNING *', [data.email.trim(), data.passwordHash, data.name || data.email.split('@')[0], data.role || 'customer']); const user = mapUser(r.rows[0]); await client.query("INSERT INTO subscriptions(user_id,plan_id,status,provider,current_period_start,current_period_end,max_devices) VALUES($1,'trial','trialing','razorpay',NOW(),NOW()+INTERVAL '7 days',2)", [user.id]); await client.query('COMMIT'); return user; } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); }
  },
  async updateUser(id: string, updates: any) { const fields: string[] = [], values: unknown[] = []; const cols: Record<string,string> = { name:'name', role:'role', isVerified:'is_verified', twoFactorEnabled:'two_factor_enabled', passwordHash:'password_hash' }; for (const [k,c] of Object.entries(cols)) if (updates[k] !== undefined) { values.push(updates[k]); fields.push(`${c}=$${values.length}`); } if (!fields.length) return this.findUserById(id); values.push(id); const r = await one<any>(`UPDATE users SET ${fields.join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING *`, values); return r ? mapUser(r) : null; },
  async deleteUser(id: string) { await pool.query('DELETE FROM users WHERE id=$1', [id]); return true; },
  async getAllUsers() { const r = await pool.query<any>('SELECT * FROM users ORDER BY created_at DESC'); return r.rows.map(mapUser).map(({ passwordHash, ...safe }) => safe); },
  async getSubscription(userId: string) { const r = await one<any>('SELECT * FROM subscriptions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1', [userId]); return r ? mapSub(r) : null; },
  async getAllSubscriptions() { return (await pool.query<any>('SELECT * FROM subscriptions ORDER BY created_at DESC')).rows.map(mapSub); },
  async findSubscriptionById(value: string) { const r = await one<any>('SELECT * FROM subscriptions WHERE id::text=$1 OR user_id::text=$1 OR razorpay_subscription_id=$1 OR stripe_subscription_id=$1 LIMIT 1', [value]); return r ? mapSub(r) : null; },
  async updateSubscription(userId: string, updates: Partial<Subscription>) {
    const current = await this.getSubscription(userId); const cols: Record<string,string> = { planId:'plan_id', status:'status', provider:'provider', currentPeriodStart:'current_period_start', currentPeriodEnd:'current_period_end', cancelAtPeriodEnd:'cancel_at_period_end', maxDevices:'max_devices', razorpaySubscriptionId:'razorpay_subscription_id', razorpayCustomerId:'razorpay_customer_id', razorpayPlanId:'razorpay_plan_id', stripeCustomerId:'stripe_customer_id', stripeSubscriptionId:'stripe_subscription_id', paymentMethodLast4:'payment_method_last4', paymentMethodBrand:'payment_method_brand' }; const fields: string[] = [], values: unknown[] = []; for (const [k,c] of Object.entries(cols)) if ((updates as any)[k] !== undefined) { values.push((updates as any)[k]); fields.push(`${c}=$${values.length}`); }
    if (!current) { const r = await one<any>(`INSERT INTO subscriptions(user_id,plan_id,status,provider,current_period_start,current_period_end,cancel_at_period_end,max_devices) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`, [userId, updates.planId || 'monthly', updates.status || 'active', updates.provider || 'razorpay', updates.currentPeriodStart || new Date().toISOString(), updates.currentPeriodEnd || new Date(Date.now()+30*86400000).toISOString(), updates.cancelAtPeriodEnd ?? false, updates.maxDevices || 2]); return mapSub(r); }
    if (!fields.length) return current; values.push(userId); const r = await one<any>(`UPDATE subscriptions SET ${fields.join(',')},updated_at=NOW() WHERE user_id=$${values.length} RETURNING *`, values); return mapSub(r);
  },
  async activateSubscription(value: string) { const s = await this.findSubscriptionById(value); return s ? this.updateSubscription(s.userId, { status:'active', cancelAtPeriodEnd:false }) : null; },
  async suspendSubscription(value: string) { const s = await this.findSubscriptionById(value); return s ? this.updateSubscription(s.userId, { status:'suspended' }) : null; },
  async recordPaymentTransaction(data: Omit<PaymentTransaction,'id'|'createdAt'>) { const r = await one<any>('INSERT INTO payment_transactions(user_id,subscription_id,provider,provider_payment_id,provider_order_id,amount,currency,status,method,error_code,error_description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *', [data.userId,data.subscriptionId||null,data.provider,data.providerPaymentId||null,data.providerOrderId||null,data.amount,data.currency,data.status,data.method||null,data.errorCode||null,data.errorDescription||null]); return mapTx(r); },
  async getAllPaymentTransactions() { return (await pool.query<any>('SELECT * FROM payment_transactions ORDER BY created_at DESC')).rows.map(mapTx); },
  async getPaymentTransactionsByUser(userId: string) { return (await pool.query<any>('SELECT * FROM payment_transactions WHERE user_id=$1 ORDER BY created_at DESC',[userId])).rows.map(mapTx); },
  async getDevicesByUser(userId: string) { return (await pool.query<any>("SELECT * FROM devices WHERE user_id=$1 AND status<>'revoked' ORDER BY paired_at DESC",[userId])).rows.map(mapDevice); },
  async getAllActiveDevices() { return (await pool.query<any>("SELECT * FROM devices WHERE status<>'revoked'")).rows.map(mapDevice); },
  async createPairingCode(userId: string, deviceType = 'windows_backend') { const code=`QB-${crypto.randomInt(1000,10000)}`, expires=new Date(Date.now()+600000); await pool.query('INSERT INTO pairing_codes(code,user_id,device_type,expires_at) VALUES($1,$2,$3,$4)',[code,userId,deviceType,expires]); return { code, expiresAt:expires.toISOString(), remainingSeconds:600 }; },
  async verifyAndConsumePairingCode(code: string, deviceName: string, hardwareFingerprint?: string, ipAddress?: string) { const client=await pool.connect(); try { await client.query('BEGIN'); const p=(await client.query<any>('SELECT * FROM pairing_codes WHERE code=$1 AND expires_at>NOW() FOR UPDATE',[code.toUpperCase().trim()])).rows[0]; if(!p){await client.query('ROLLBACK');return null;} const sub=await this.getSubscription(p.user_id), devices=await this.getDevicesByUser(p.user_id); if(devices.length >= (sub?.maxDevices||2)) throw new Error(`Device limit reached for plan (${devices.length}/${sub?.maxDevices||2}).`); const r=await client.query<any>("INSERT INTO devices(user_id,device_name,device_type,hardware_fingerprint,ip_address,status,last_heartbeat_at) VALUES($1,$2,$3,$4,$5,'online',NOW()) RETURNING *",[p.user_id,deviceName||'QBot2 device',p.device_type,hardwareFingerprint||null,ipAddress||null]); await client.query('DELETE FROM pairing_codes WHERE code=$1',[p.code]); await client.query('COMMIT'); return mapDevice(r.rows[0]); } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} },
  async revokeDevice(deviceId: string, userId?: string) { const values=userId?[deviceId,userId]:[deviceId]; const r=await one<any>(`UPDATE devices SET status='revoked' WHERE id::text=$1 ${userId?'AND user_id::text=$2':''} RETURNING id`,values); return !!r; },
  async updateDeviceHeartbeat(deviceId: string, ipAddress?: string) { const r=await one<any>("UPDATE devices SET status='online',last_heartbeat_at=NOW(),ip_address=COALESCE($2,ip_address) WHERE id::text=$1 AND status<>'revoked' RETURNING *",[deviceId,ipAddress||null]); return r?mapDevice(r):null; },
  async isWebhookEventProcessed(eventId: string) { return !!(await one<any>('SELECT 1 FROM webhook_events WHERE event_id=$1',[eventId])); },
  async logWebhookEvent(eventId: string,eventType: string,status:'processed'|'failed'|'ignored',summary:string,payload?:any) { const r=await one<any>('INSERT INTO webhook_events(event_id,event_type,status,summary,payload) VALUES($1,$2,$3,$4,$5) ON CONFLICT(event_id) DO UPDATE SET status=EXCLUDED.status,summary=EXCLUDED.summary,payload=EXCLUDED.payload,processed_at=NOW() RETURNING *',[eventId,eventType,status,summary,payload||{}]); return mapWebhook(r); },
  async getRecentWebhookEvents(limit=30) { return (await pool.query<any>('SELECT * FROM webhook_events ORDER BY processed_at DESC LIMIT $1',[limit])).rows.map(mapWebhook); },
  async logAudit(userId:string|undefined,action:string,details:string,ipAddress?:string) { const r=await one<any>('INSERT INTO audit_logs(user_id,action,details,ip_address) VALUES($1,$2,$3,$4) RETURNING *',[userId||null,action,details,ipAddress||null]); return {id:String(r.id),userId:r.user_id?String(r.user_id):undefined,action:r.action,details:r.details,ipAddress:r.ip_address||undefined,timestamp:new Date(r.created_at).toISOString()} as AuditLog; },
  async getAuditLogs(limit=50) { return (await pool.query<any>('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT $1',[limit])).rows; },
  async getSupportNotes(userId:string) { return (await pool.query<any>('SELECT * FROM support_notes WHERE user_id=$1 ORDER BY created_at DESC',[userId])).rows.map(r=>({id:String(r.id),userId:String(r.user_id),author:r.author,content:r.content,createdAt:new Date(r.created_at).toISOString()} as SupportNote)); },
  async addSupportNote(userId:string,author:string,content:string) { const r=await one<any>('INSERT INTO support_notes(user_id,author,content) VALUES($1,$2,$3) RETURNING *',[userId,author,content]); return {id:String(r.id),userId:String(r.user_id),author:r.author,content:r.content,createdAt:new Date(r.created_at).toISOString()} as SupportNote; },
  async getAdminMetrics():Promise<AdminMetrics> { const r=await one<any>("SELECT COUNT(*) FILTER(WHERE u.role='customer') total_customers,COUNT(*) FILTER(WHERE s.status='active') active_subscriptions,COUNT(*) FILTER(WHERE s.status IN ('trialing','pending')) trial_users,COUNT(*) FILTER(WHERE s.status IN ('expired','canceled')) expired_subscriptions,COUNT(*) FILTER(WHERE s.status IN ('past_due','unpaid','halted')) failed_payments,COUNT(d.id) FILTER(WHERE d.status='online') active_devices_count FROM users u LEFT JOIN subscriptions s ON s.user_id=u.id LEFT JOIN devices d ON d.user_id=u.id"); const m=await one<any>("SELECT COALESCE(SUM(CASE WHEN plan_id='monthly' THEN 49 WHEN plan_id='annual' THEN 470.0/12 ELSE 0 END),0) mrr FROM subscriptions WHERE status='active'"); return {totalCustomers:Number(r.total_customers),activeSubscriptions:Number(r.active_subscriptions),trialUsers:Number(r.trial_users),expiredSubscriptions:Number(r.expired_subscriptions),failedPayments:Number(r.failed_payments),activeDevicesCount:Number(r.active_devices_count),mrr:Number(m.mrr)}; }
};
